# This is the compose file for the production roboe backend
version: "3.9"
services:
  #FastAPI Server
  server:
    build:
      context: ./
      dockerfile: docker/Dockerfile.prod
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      #server configuration
      SQLITE_FILE: database.db
      SECRET_KEY: ${SECRET_KEY}

