# This is the compose file for the production roboe backend
version: "3.9"
services:
  #FastAPI Server
  server:
    build:
      context: ./
      dockerfile: docker/Dockerfile.prod
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      #database configuration
      MONGO_HOST: mongo
      MONGO_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}

