---
openapi: 3.0.2
info:
  title: roboe backend
  description: |2

    ### backend server for the roboapp, connecting roboe with the android clients
  contact:
    name: ''
    url: https://github.com/open-roboe
  version: 0.0.1
paths:
  "/api/account/":
    get:
      tags:
      - account
      summary: Get Logged User
      description: Returns account info, requires authentication
      operationId: get_logged_user_api_account__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserResponse"
      security:
      - OAuth2PasswordBearer: []

components:
  schemas:
    Body_login_api_account_auth_post:
      title: Body_login_api_account_auth_post
      required:
      - username
      - password
      type: object
      properties:
        grant_type:
          title: Grant Type
          pattern: password
          type: string
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        scope:
          title: Scope
          type: string
          default: ''
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    Course:
      title: Course
      required:
      - name
      type: object
      properties:
        name:
          title: Name
          type: string
        data:
          title: Data
          type: string
          default: ''
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            "$ref": "#/components/schemas/ValidationError"
    PollResponse:
      title: PollResponse
      required:
      - courses
      - users
      - roboas
      type: object
      properties:
        courses:
          title: Courses
          type: array
          items:
            "$ref": "#/components/schemas/Course"
        users:
          title: Users
          type: array
          items:
            "$ref": "#/components/schemas/UserResponse"
        roboas:
          title: Roboas
          type: array
          items:
            "$ref": "#/components/schemas/RoboaResponse"
    PollRoboaUpdate:
      title: PollRoboaUpdate
      required:
      - lat
      - lon
      type: object
      properties:
        lat:
          title: Lat
          type: number
        lon:
          title: Lon
          type: number
    PollUserUpdate:
      title: PollUserUpdate
      required:
      - lat
      - lon
      type: object
      properties:
        lat:
          title: Lat
          type: number
        lon:
          title: Lon
          type: number
    RoboaResponse:
      title: RoboaResponse
      required:
      - name
      - last_update
      type: object
      properties:
        name:
          title: Name
          type: string
        last_update:
          title: Last Update
          type: integer
        lat:
          title: Lat
          type: number
          default: 0
        lon:
          title: Lon
          type: number
          default: 0
        course_id:
          title: Course Id
          type: string
    UserCreate:
      title: UserCreate
      required:
      - username
      - password
      type: object
      properties:
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        admin:
          title: Admin
          type: boolean
          default: false
        super_admin:
          title: Super Admin
          type: boolean
          default: false
    UserResponse:
      title: UserResponse
      required:
      - username
      - last_update
      type: object
      properties:
        username:
          title: Username
          type: string
        admin:
          title: Admin
          type: boolean
          default: true
        super_admin:
          title: Super Admin
          type: boolean
          default: false
        last_update:
          title: Last Update
          type: integer
        lat:
          title: Lat
          type: number
          default: 0
        lon:
          title: Lon
          type: number
          default: 0
        course_id:
          title: Course Id
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: "/api/account/auth"
