# OpenAPI Generator Plus generator configuration
#
# The path (relative to this configuration file) or a URL for your API specification
inputPath: api.yml

# The path (relative to this configuration file) where the generated API should be output
outputPath: dist

# The name of the generator template used
generator: "@openapi-generator-plus/java-retrofit-client-generator"

# See https://github.com/karlvr/openapi-generator-plus-generators/tree/master/packages/java-retrofit-client#readme for more configuration options
