/*
 * roboe backend
 *  ### backend server for the roboapp, connecting roboe with the android clients 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.roboapp2.api.definition.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.roboapp2.api.definition.model.ApiBuoy;
import com.example.roboapp2.api.definition.model.ApiJury;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiCourse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-01T12:48:53.094523Z[Etc/UTC]")
public class ApiCourse {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_COMPASS_DEGREES = "compass_degrees";
  @SerializedName(SERIALIZED_NAME_COMPASS_DEGREES)
  private Integer compassDegrees;

  public static final String SERIALIZED_NAME_START_LINE_LEN = "start_line_len";
  @SerializedName(SERIALIZED_NAME_START_LINE_LEN)
  private BigDecimal startLineLen;

  public static final String SERIALIZED_NAME_BREAK_DISTANCE = "break_distance";
  @SerializedName(SERIALIZED_NAME_BREAK_DISTANCE)
  private BigDecimal breakDistance;

  public static final String SERIALIZED_NAME_COURSE_LENGTH = "course_length";
  @SerializedName(SERIALIZED_NAME_COURSE_LENGTH)
  private BigDecimal courseLength;

  public static final String SERIALIZED_NAME_BOTTOM_BUOY = "bottom_buoy";
  @SerializedName(SERIALIZED_NAME_BOTTOM_BUOY)
  private Boolean bottomBuoy;

  public static final String SERIALIZED_NAME_GATE = "gate";
  @SerializedName(SERIALIZED_NAME_GATE)
  private Boolean gate;

  public static final String SERIALIZED_NAME_SECOND_MARK_DISTANCE = "second_mark_distance";
  @SerializedName(SERIALIZED_NAME_SECOND_MARK_DISTANCE)
  private BigDecimal secondMarkDistance;

  public static final String SERIALIZED_NAME_CREATION_DATE = "creation_date";
  @SerializedName(SERIALIZED_NAME_CREATION_DATE)
  private Integer creationDate;

  public static final String SERIALIZED_NAME_JURY = "jury";
  @SerializedName(SERIALIZED_NAME_JURY)
  private ApiJury jury;

  public static final String SERIALIZED_NAME_BUOYS = "buoys";
  @SerializedName(SERIALIZED_NAME_BUOYS)
  private List<ApiBuoy> buoys = new ArrayList<>();

  public ApiCourse() {
  }

  public ApiCourse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ApiCourse type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public ApiCourse compassDegrees(Integer compassDegrees) {
    
    this.compassDegrees = compassDegrees;
    return this;
  }

   /**
   * Get compassDegrees
   * @return compassDegrees
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCompassDegrees() {
    return compassDegrees;
  }


  public void setCompassDegrees(Integer compassDegrees) {
    this.compassDegrees = compassDegrees;
  }


  public ApiCourse startLineLen(BigDecimal startLineLen) {
    
    this.startLineLen = startLineLen;
    return this;
  }

   /**
   * Get startLineLen
   * @return startLineLen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getStartLineLen() {
    return startLineLen;
  }


  public void setStartLineLen(BigDecimal startLineLen) {
    this.startLineLen = startLineLen;
  }


  public ApiCourse breakDistance(BigDecimal breakDistance) {
    
    this.breakDistance = breakDistance;
    return this;
  }

   /**
   * Get breakDistance
   * @return breakDistance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getBreakDistance() {
    return breakDistance;
  }


  public void setBreakDistance(BigDecimal breakDistance) {
    this.breakDistance = breakDistance;
  }


  public ApiCourse courseLength(BigDecimal courseLength) {
    
    this.courseLength = courseLength;
    return this;
  }

   /**
   * Get courseLength
   * @return courseLength
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getCourseLength() {
    return courseLength;
  }


  public void setCourseLength(BigDecimal courseLength) {
    this.courseLength = courseLength;
  }


  public ApiCourse bottomBuoy(Boolean bottomBuoy) {
    
    this.bottomBuoy = bottomBuoy;
    return this;
  }

   /**
   * Get bottomBuoy
   * @return bottomBuoy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getBottomBuoy() {
    return bottomBuoy;
  }


  public void setBottomBuoy(Boolean bottomBuoy) {
    this.bottomBuoy = bottomBuoy;
  }


  public ApiCourse gate(Boolean gate) {
    
    this.gate = gate;
    return this;
  }

   /**
   * Get gate
   * @return gate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getGate() {
    return gate;
  }


  public void setGate(Boolean gate) {
    this.gate = gate;
  }


  public ApiCourse secondMarkDistance(BigDecimal secondMarkDistance) {
    
    this.secondMarkDistance = secondMarkDistance;
    return this;
  }

   /**
   * Get secondMarkDistance
   * @return secondMarkDistance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getSecondMarkDistance() {
    return secondMarkDistance;
  }


  public void setSecondMarkDistance(BigDecimal secondMarkDistance) {
    this.secondMarkDistance = secondMarkDistance;
  }


  public ApiCourse creationDate(Integer creationDate) {
    
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCreationDate() {
    return creationDate;
  }


  public void setCreationDate(Integer creationDate) {
    this.creationDate = creationDate;
  }


  public ApiCourse jury(ApiJury jury) {
    
    this.jury = jury;
    return this;
  }

   /**
   * Get jury
   * @return jury
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ApiJury getJury() {
    return jury;
  }


  public void setJury(ApiJury jury) {
    this.jury = jury;
  }


  public ApiCourse buoys(List<ApiBuoy> buoys) {
    
    this.buoys = buoys;
    return this;
  }

  public ApiCourse addBuoysItem(ApiBuoy buoysItem) {
    this.buoys.add(buoysItem);
    return this;
  }

   /**
   * Get buoys
   * @return buoys
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<ApiBuoy> getBuoys() {
    return buoys;
  }


  public void setBuoys(List<ApiBuoy> buoys) {
    this.buoys = buoys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiCourse apiCourse = (ApiCourse) o;
    return Objects.equals(this.name, apiCourse.name) &&
        Objects.equals(this.type, apiCourse.type) &&
        Objects.equals(this.compassDegrees, apiCourse.compassDegrees) &&
        Objects.equals(this.startLineLen, apiCourse.startLineLen) &&
        Objects.equals(this.breakDistance, apiCourse.breakDistance) &&
        Objects.equals(this.courseLength, apiCourse.courseLength) &&
        Objects.equals(this.bottomBuoy, apiCourse.bottomBuoy) &&
        Objects.equals(this.gate, apiCourse.gate) &&
        Objects.equals(this.secondMarkDistance, apiCourse.secondMarkDistance) &&
        Objects.equals(this.creationDate, apiCourse.creationDate) &&
        Objects.equals(this.jury, apiCourse.jury) &&
        Objects.equals(this.buoys, apiCourse.buoys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, compassDegrees, startLineLen, breakDistance, courseLength, bottomBuoy, gate, secondMarkDistance, creationDate, jury, buoys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiCourse {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    compassDegrees: ").append(toIndentedString(compassDegrees)).append("\n");
    sb.append("    startLineLen: ").append(toIndentedString(startLineLen)).append("\n");
    sb.append("    breakDistance: ").append(toIndentedString(breakDistance)).append("\n");
    sb.append("    courseLength: ").append(toIndentedString(courseLength)).append("\n");
    sb.append("    bottomBuoy: ").append(toIndentedString(bottomBuoy)).append("\n");
    sb.append("    gate: ").append(toIndentedString(gate)).append("\n");
    sb.append("    secondMarkDistance: ").append(toIndentedString(secondMarkDistance)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    jury: ").append(toIndentedString(jury)).append("\n");
    sb.append("    buoys: ").append(toIndentedString(buoys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

