/*
 * roboe backend
 *  ### backend server for the roboapp, connecting roboe with the android clients 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.roboapp2.api.definition.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.roboapp2.api.definition.model.Buoy;
import com.example.roboapp2.api.definition.model.JuryResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CourseResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-31T15:49:23.851875Z[Etc/UTC]")
public class CourseResponse {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_COMPASS_DEGREES = "compass_degrees";
  @SerializedName(SERIALIZED_NAME_COMPASS_DEGREES)
  private Integer compassDegrees;

  public static final String SERIALIZED_NAME_START_LINE_LEN = "start_line_len";
  @SerializedName(SERIALIZED_NAME_START_LINE_LEN)
  private Integer startLineLen;

  public static final String SERIALIZED_NAME_BREAK_DISTANCE = "break_distance";
  @SerializedName(SERIALIZED_NAME_BREAK_DISTANCE)
  private Integer breakDistance;

  public static final String SERIALIZED_NAME_BOTTOM_BUOY = "bottom_buoy";
  @SerializedName(SERIALIZED_NAME_BOTTOM_BUOY)
  private Integer bottomBuoy;

  public static final String SERIALIZED_NAME_GATE = "gate";
  @SerializedName(SERIALIZED_NAME_GATE)
  private Boolean gate;

  public static final String SERIALIZED_NAME_SECOND_MARK_DISTANCE = "second_mark_distance";
  @SerializedName(SERIALIZED_NAME_SECOND_MARK_DISTANCE)
  private Integer secondMarkDistance;

  public static final String SERIALIZED_NAME_CREATION_DATE = "creation_date";
  @SerializedName(SERIALIZED_NAME_CREATION_DATE)
  private Integer creationDate;

  public static final String SERIALIZED_NAME_JURY = "jury";
  @SerializedName(SERIALIZED_NAME_JURY)
  private JuryResponse jury;

  public static final String SERIALIZED_NAME_BUOYS = "buoys";
  @SerializedName(SERIALIZED_NAME_BUOYS)
  private List<Buoy> buoys = new ArrayList<>();

  public CourseResponse() {
  }

  public CourseResponse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CourseResponse type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public CourseResponse compassDegrees(Integer compassDegrees) {
    
    this.compassDegrees = compassDegrees;
    return this;
  }

   /**
   * Get compassDegrees
   * @return compassDegrees
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCompassDegrees() {
    return compassDegrees;
  }


  public void setCompassDegrees(Integer compassDegrees) {
    this.compassDegrees = compassDegrees;
  }


  public CourseResponse startLineLen(Integer startLineLen) {
    
    this.startLineLen = startLineLen;
    return this;
  }

   /**
   * Get startLineLen
   * @return startLineLen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getStartLineLen() {
    return startLineLen;
  }


  public void setStartLineLen(Integer startLineLen) {
    this.startLineLen = startLineLen;
  }


  public CourseResponse breakDistance(Integer breakDistance) {
    
    this.breakDistance = breakDistance;
    return this;
  }

   /**
   * Get breakDistance
   * @return breakDistance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getBreakDistance() {
    return breakDistance;
  }


  public void setBreakDistance(Integer breakDistance) {
    this.breakDistance = breakDistance;
  }


  public CourseResponse bottomBuoy(Integer bottomBuoy) {
    
    this.bottomBuoy = bottomBuoy;
    return this;
  }

   /**
   * Get bottomBuoy
   * @return bottomBuoy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getBottomBuoy() {
    return bottomBuoy;
  }


  public void setBottomBuoy(Integer bottomBuoy) {
    this.bottomBuoy = bottomBuoy;
  }


  public CourseResponse gate(Boolean gate) {
    
    this.gate = gate;
    return this;
  }

   /**
   * Get gate
   * @return gate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getGate() {
    return gate;
  }


  public void setGate(Boolean gate) {
    this.gate = gate;
  }


  public CourseResponse secondMarkDistance(Integer secondMarkDistance) {
    
    this.secondMarkDistance = secondMarkDistance;
    return this;
  }

   /**
   * Get secondMarkDistance
   * @return secondMarkDistance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSecondMarkDistance() {
    return secondMarkDistance;
  }


  public void setSecondMarkDistance(Integer secondMarkDistance) {
    this.secondMarkDistance = secondMarkDistance;
  }


  public CourseResponse creationDate(Integer creationDate) {
    
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getCreationDate() {
    return creationDate;
  }


  public void setCreationDate(Integer creationDate) {
    this.creationDate = creationDate;
  }


  public CourseResponse jury(JuryResponse jury) {
    
    this.jury = jury;
    return this;
  }

   /**
   * Get jury
   * @return jury
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public JuryResponse getJury() {
    return jury;
  }


  public void setJury(JuryResponse jury) {
    this.jury = jury;
  }


  public CourseResponse buoys(List<Buoy> buoys) {
    
    this.buoys = buoys;
    return this;
  }

  public CourseResponse addBuoysItem(Buoy buoysItem) {
    this.buoys.add(buoysItem);
    return this;
  }

   /**
   * Get buoys
   * @return buoys
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<Buoy> getBuoys() {
    return buoys;
  }


  public void setBuoys(List<Buoy> buoys) {
    this.buoys = buoys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CourseResponse courseResponse = (CourseResponse) o;
    return Objects.equals(this.name, courseResponse.name) &&
        Objects.equals(this.type, courseResponse.type) &&
        Objects.equals(this.compassDegrees, courseResponse.compassDegrees) &&
        Objects.equals(this.startLineLen, courseResponse.startLineLen) &&
        Objects.equals(this.breakDistance, courseResponse.breakDistance) &&
        Objects.equals(this.bottomBuoy, courseResponse.bottomBuoy) &&
        Objects.equals(this.gate, courseResponse.gate) &&
        Objects.equals(this.secondMarkDistance, courseResponse.secondMarkDistance) &&
        Objects.equals(this.creationDate, courseResponse.creationDate) &&
        Objects.equals(this.jury, courseResponse.jury) &&
        Objects.equals(this.buoys, courseResponse.buoys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, compassDegrees, startLineLen, breakDistance, bottomBuoy, gate, secondMarkDistance, creationDate, jury, buoys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CourseResponse {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    compassDegrees: ").append(toIndentedString(compassDegrees)).append("\n");
    sb.append("    startLineLen: ").append(toIndentedString(startLineLen)).append("\n");
    sb.append("    breakDistance: ").append(toIndentedString(breakDistance)).append("\n");
    sb.append("    bottomBuoy: ").append(toIndentedString(bottomBuoy)).append("\n");
    sb.append("    gate: ").append(toIndentedString(gate)).append("\n");
    sb.append("    secondMarkDistance: ").append(toIndentedString(secondMarkDistance)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    jury: ").append(toIndentedString(jury)).append("\n");
    sb.append("    buoys: ").append(toIndentedString(buoys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

