/*
 * roboe backend
 *  ### backend server for the roboapp, connecting roboe with the android clients 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.roboapp2.api.definition.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.roboapp2.api.definition.model.Buoy;
import com.example.roboapp2.api.definition.model.BuoyJury;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CourseResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-27T10:30:03.689852Z[Etc/UTC]")
public class CourseResponse {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_JURY = "jury";
  @SerializedName(SERIALIZED_NAME_JURY)
  private BuoyJury jury;

  public static final String SERIALIZED_NAME_BUOYS = "buoys";
  @SerializedName(SERIALIZED_NAME_BUOYS)
  private List<Buoy> buoys = new ArrayList<>();

  public CourseResponse() {
  }

  public CourseResponse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CourseResponse type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public CourseResponse jury(BuoyJury jury) {
    
    this.jury = jury;
    return this;
  }

   /**
   * Get jury
   * @return jury
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BuoyJury getJury() {
    return jury;
  }


  public void setJury(BuoyJury jury) {
    this.jury = jury;
  }


  public CourseResponse buoys(List<Buoy> buoys) {
    
    this.buoys = buoys;
    return this;
  }

  public CourseResponse addBuoysItem(Buoy buoysItem) {
    this.buoys.add(buoysItem);
    return this;
  }

   /**
   * Get buoys
   * @return buoys
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<Buoy> getBuoys() {
    return buoys;
  }


  public void setBuoys(List<Buoy> buoys) {
    this.buoys = buoys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CourseResponse courseResponse = (CourseResponse) o;
    return Objects.equals(this.name, courseResponse.name) &&
        Objects.equals(this.type, courseResponse.type) &&
        Objects.equals(this.jury, courseResponse.jury) &&
        Objects.equals(this.buoys, courseResponse.buoys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, jury, buoys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CourseResponse {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    jury: ").append(toIndentedString(jury)).append("\n");
    sb.append("    buoys: ").append(toIndentedString(buoys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

