/*
 * roboe backend
 *  ### backend server for the roboapp, connecting roboe with the android clients 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.roboapp2.api.definition.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * RoboaResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-01T12:48:53.094523Z[Etc/UTC]")
public class RoboaResponse {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_LAST_UPDATE = "last_update";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATE)
  private Integer lastUpdate;

  public static final String SERIALIZED_NAME_LAT = "lat";
  @SerializedName(SERIALIZED_NAME_LAT)
  private BigDecimal lat = new BigDecimal("0");

  public static final String SERIALIZED_NAME_LON = "lon";
  @SerializedName(SERIALIZED_NAME_LON)
  private BigDecimal lon = new BigDecimal("0");

  public static final String SERIALIZED_NAME_ETA = "eta";
  @SerializedName(SERIALIZED_NAME_ETA)
  private Integer eta = 0;

  public static final String SERIALIZED_NAME_ASSIGNED_BUOY = "assigned_buoy";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_BUOY)
  private Integer assignedBuoy;

  public static final String SERIALIZED_NAME_TARGET_LAT = "target_lat";
  @SerializedName(SERIALIZED_NAME_TARGET_LAT)
  private BigDecimal targetLat = new BigDecimal("0");

  public static final String SERIALIZED_NAME_TARGET_LON = "target_lon";
  @SerializedName(SERIALIZED_NAME_TARGET_LON)
  private BigDecimal targetLon = new BigDecimal("0");

  public RoboaResponse() {
  }

  public RoboaResponse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public RoboaResponse lastUpdate(Integer lastUpdate) {
    
    this.lastUpdate = lastUpdate;
    return this;
  }

   /**
   * Get lastUpdate
   * @return lastUpdate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getLastUpdate() {
    return lastUpdate;
  }


  public void setLastUpdate(Integer lastUpdate) {
    this.lastUpdate = lastUpdate;
  }


  public RoboaResponse lat(BigDecimal lat) {
    
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getLat() {
    return lat;
  }


  public void setLat(BigDecimal lat) {
    this.lat = lat;
  }


  public RoboaResponse lon(BigDecimal lon) {
    
    this.lon = lon;
    return this;
  }

   /**
   * Get lon
   * @return lon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getLon() {
    return lon;
  }


  public void setLon(BigDecimal lon) {
    this.lon = lon;
  }


  public RoboaResponse eta(Integer eta) {
    
    this.eta = eta;
    return this;
  }

   /**
   * Get eta
   * @return eta
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getEta() {
    return eta;
  }


  public void setEta(Integer eta) {
    this.eta = eta;
  }


  public RoboaResponse assignedBuoy(Integer assignedBuoy) {
    
    this.assignedBuoy = assignedBuoy;
    return this;
  }

   /**
   * Get assignedBuoy
   * @return assignedBuoy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAssignedBuoy() {
    return assignedBuoy;
  }


  public void setAssignedBuoy(Integer assignedBuoy) {
    this.assignedBuoy = assignedBuoy;
  }


  public RoboaResponse targetLat(BigDecimal targetLat) {
    
    this.targetLat = targetLat;
    return this;
  }

   /**
   * Get targetLat
   * @return targetLat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getTargetLat() {
    return targetLat;
  }


  public void setTargetLat(BigDecimal targetLat) {
    this.targetLat = targetLat;
  }


  public RoboaResponse targetLon(BigDecimal targetLon) {
    
    this.targetLon = targetLon;
    return this;
  }

   /**
   * Get targetLon
   * @return targetLon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getTargetLon() {
    return targetLon;
  }


  public void setTargetLon(BigDecimal targetLon) {
    this.targetLon = targetLon;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoboaResponse roboaResponse = (RoboaResponse) o;
    return Objects.equals(this.name, roboaResponse.name) &&
        Objects.equals(this.lastUpdate, roboaResponse.lastUpdate) &&
        Objects.equals(this.lat, roboaResponse.lat) &&
        Objects.equals(this.lon, roboaResponse.lon) &&
        Objects.equals(this.eta, roboaResponse.eta) &&
        Objects.equals(this.assignedBuoy, roboaResponse.assignedBuoy) &&
        Objects.equals(this.targetLat, roboaResponse.targetLat) &&
        Objects.equals(this.targetLon, roboaResponse.targetLon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, lastUpdate, lat, lon, eta, assignedBuoy, targetLat, targetLon);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoboaResponse {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    eta: ").append(toIndentedString(eta)).append("\n");
    sb.append("    assignedBuoy: ").append(toIndentedString(assignedBuoy)).append("\n");
    sb.append("    targetLat: ").append(toIndentedString(targetLat)).append("\n");
    sb.append("    targetLon: ").append(toIndentedString(targetLon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

