apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboapp
spec:
  selector:
    matchLabels:
      app: roboapp
  revisionHistoryLimit: 3
  replicas: 1
  template:
    metadata:
      labels:
        app: roboapp
    spec:
      containers:
        - name: roboapp
          image: ghcr.io/open-roboe/backend:sha-814a1fa26fc3caf20dc6c5faa25c8860903e4363
          env:
            - name: SQLITE_FILE
              value: test.db
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: roboapp-secrets
                  key: SECRET_KEY
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
